# Generated by Django 3.2.5 on 2021-07-31 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quote', '0002_alter_quoteitem_discount'),
    ]

    operations = [
        migrations.AddField(
            model_name='quoteitem',
            name='price',
            field=models.PositiveIntegerField(default=0, verbose_name='price'),
        ),
    ]
