# Generated by Django 3.2.5 on 2021-07-21 17:16

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django_jalali.db.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '0002_auto_20210721_1716'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OrganizationProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='organization product name')),
                ('slug', models.SlugField(editable=False, unique=True)),
                ('created_date', django_jalali.db.models.jDateField(auto_now_add=True, verbose_name='organization product created date')),
                ('product_suggestion', models.ManyToManyField(to='product.Product')),
            ],
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', django_jalali.db.models.jDateTimeField(auto_now_add=True, verbose_name='create time')),
                ('name', models.CharField(max_length=50, verbose_name='organization name')),
                ('slug', models.SlugField(editable=False, unique=True)),
                ('city', models.CharField(max_length=20, verbose_name='organization city')),
                ('organization_phone_number', models.CharField(max_length=11, validators=[django.core.validators.RegexValidator(message='organization phone number invalid', regex='^0[1-9]{2}[0-9]{8}$')], verbose_name='organization phone number')),
                ('organization_email', models.EmailField(max_length=254, verbose_name='organization email address')),
                ('number_of_employees', models.CharField(max_length=6, validators=[django.core.validators.RegexValidator(message='input invalid', regex='^[1-9]{1}[0-9]*$')], verbose_name='number of employees')),
                ('purchasing_officer_name', models.CharField(max_length=50, verbose_name='purchasing officer name')),
                ('purchasing_officer_phone_number', models.CharField(max_length=11, validators=[django.core.validators.RegexValidator(message='phone number invalid', regex='^09[0-9]{9}$')], verbose_name='purchasing officer phone number')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='creator')),
                ('organization_product', models.ManyToManyField(to='organization.OrganizationProduct')),
            ],
        ),
    ]
