# Generated by Django 3.2.5 on 2021-07-22 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='organizationproduct',
            old_name='product_suggestion',
            new_name='products_suggestion',
        ),
        migrations.AlterField(
            model_name='organization',
            name='organization_product',
            field=models.ManyToManyField(blank=True, to='organization.OrganizationProduct'),
        ),
    ]
