# Generated by Django 3.2.5 on 2021-07-22 07:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0002_auto_20210722_0741'),
    ]

    operations = [
        migrations.RenameField(
            model_name='organization',
            old_name='organization_product',
            new_name='organization_products',
        ),
    ]
