# Generated by Django 3.2.5 on 2021-07-27 14:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0003_rename_organization_product_organization_organization_products'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='city',
            field=models.CharField(max_length=20, unique=True, verbose_name='organization city'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='name',
            field=models.CharField(max_length=50, unique=True, verbose_name='organization name'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='organization_email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='organization email address'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='organization_phone_number',
            field=models.CharField(max_length=11, unique=True, validators=[django.core.validators.RegexValidator(message='organization phone number invalid', regex='^0[1-9]{2}[0-9]{8}$')], verbose_name='organization phone number'),
        ),
        migrations.AlterField(
            model_name='organizationproduct',
            name='name',
            field=models.CharField(max_length=50, unique=True, verbose_name='organization product name'),
        ),
    ]
