# Generated by Django 3.2.5 on 2021-07-21 11:54

from django.db import migrations, models
import django_jalali.db.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='product name')),
                ('created_date', django_jalali.db.models.jDateField(auto_now_add=True, verbose_name='product created date')),
                ('price', models.PositiveIntegerField(verbose_name='product price')),
                ('tax_status', models.BooleanField(default=True, verbose_name='product tax status')),
                ('technical_specification', models.TextField(verbose_name='product technical specification')),
                ('catalogue_image', models.ImageField(blank=True, null=True, upload_to='image', verbose_name='product catalogue image')),
                ('catalogue_pdf', models.FileField(blank=True, null=True, upload_to='pdf', verbose_name='product catalogue pdf')),
                ('slug', models.SlugField(unique=True, verbose_name='product slug')),
            ],
        ),
    ]
