# Generated by Django 3.2.5 on 2021-07-28 13:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_jalali.db.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', django_jalali.db.models.jDateTimeField(auto_now_add=True, verbose_name='create time')),
                ('email_status', models.BooleanField(default=True, verbose_name='email status')),
                ('email', models.CharField(max_length=50, verbose_name='email')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='creator')),
            ],
        ),
    ]
