# Generated by Django 3.2.5 on 2021-07-25 06:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_jalali.db.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('organization', '0003_rename_organization_product_organization_organization_products'),
    ]

    operations = [
        migrations.CreateModel(
            name='FollowUp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, unique=True, verbose_name='follow up title')),
                ('slug', models.SlugField(editable=False, unique=True)),
                ('created_time', django_jalali.db.models.jDateTimeField(auto_now_add=True, verbose_name='follow up created time')),
                ('body', models.TextField(verbose_name='follow up body')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='creator')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='organization.organization', verbose_name='organization')),
            ],
        ),
    ]
