# Generated by Django 3.2.5 on 2021-07-25 06:19

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0003_rename_organization_product_organization_organization_products'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('followup', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='followup',
            name='slug',
            field=models.SlugField(editable=False),
        ),
        migrations.AlterField(
            model_name='followup',
            name='title',
            field=models.CharField(max_length=50, verbose_name='follow up title'),
        ),
        migrations.AlterUniqueTogether(
            name='followup',
            unique_together={('title', 'creator', 'organization')},
        ),
    ]
