# Generated by Django 3.2.5 on 2021-07-25 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('followup', '0002_auto_20210725_0619'),
    ]

    operations = [
        migrations.AlterField(
            model_name='followup',
            name='slug',
            field=models.SlugField(editable=False, unique=True),
        ),
    ]
